### ISSUE TITLE
cache: invalidate cache after configuration changed

### ISSUE THREAD

**Issue by zhenghaoz** [gorse-io/gorse#348]
In the current implementation, users have to clear the cache manually to apply the latest configuration. It would be better to invalidate cache automatically when configuration changed.

## Design

Refresh cache when the configuration changed.

- **User neighbors cache** is affected by the following configs:

```toml
[recommend]

# The cache size for recommended/popular/latest items. The default value is 10.
cache_size = 100

[recommend.user_neighbors]

# The type of neighbors for users. There are three types:
#   similar: Neighbors are found by number of common labels.
#   related: Neighbors are found by number of common liked items.
#   auto: If a user have labels, neighbors are found by number of common labels.
#         If this user have no labels, neighbors are found by number of common liked items.
# The default value is "auto".
neighbor_type = "similar"

# Enable approximate user neighbor searching using vector index. The default value is true.
enable_index = true

# Minimal recall for approximate user neighbor searching. The default value is 0.8.
index_recall = 0.8

# Maximal number of fit epochs for approximate user neighbor searching vector index. The default value is 3.
index_fit_epoch = 3
```

- **Item neighbors cache** is affected by the following configs:

```toml
[recommend.item_neighbors]

# The type of neighbors for items. There are three types:
#   similar: Neighbors are found by number of common labels.
#   related: Neighbors are found by number of common users.
#   auto: If a item have labels, neighbors are found by number of common labels.
#         If this item have no labels, neighbors are found by number of common users.
# The default value is "auto".
neighbor_type = "similar"

# Enable approximate item neighbor searching using vector index. The default value is true.
enable_index = true

# Minimal recall for approximate item neighbor searching. The default value is 0.8.
index_recall = 0.8

# Maximal number of fit epochs for approximate item neighbor searching vector index. The default value is 3.
index_fit_epoch = 3
```

- **Offline recommendation cache** is affected by the following configs:

```toml
[recommend.collaborative]

# Enable approximate collaborative filtering recommend using vector index. The default value is true.
enable_index = true

# Minimal recall for approximate collaborative filtering recommend. The default value is 0.9.
index_recall = 0.9

# Maximal number of fit epochs for approximate collaborative filtering recommend vector index. The default value is 3.
index_fit_epoch = 3
```

## Implementation

1. Generate MD5 digest for dependent configurations ([config.go](https://github.com/zhenghaoz/gorse/blob/master/config/config.go)). e.g.:

```go
func (config *Config) UserNeighborDigest() string {
  // Generate MD5 digest for dependent configurations
}
```

2. Save digest to cache when updating user (item) neighbors. e.g.:

Add 

```go
if err := m.CacheClient.SetString(cache.Key(cache.ItemNeighborsDigest, dataset.ItemIndex.ToName(int32(itemId)), category), digest); err != nil {
  return errors.Trace(err)
}
```

before

https://github.com/zhenghaoz/gorse/blob/f2f7f59f78fcd23fe2e1bad879785b268ba43591/master/tasks.go#L307-L310

3. Compare digests in `checkUserNeighborCacheTimeout`:

https://github.com/zhenghaoz/gorse/blob/f2f7f59f78fcd23fe2e1bad879785b268ba43591/master/tasks.go#L641-L658

4. Add tests to ensure converage.
