### ISSUE TITLE
Support https for clickhouse connection

### ISSUE THREAD

**Issue by sadokbayar** [gorse-io/gorse#468]
Add support for  https clickhouse for datastore connection:

in database.go, change the hardcoded "http://" to support "https://"
else if strings.HasPrefix(path, clickhousePrefix) {
		uri := "http://" + path[len(clickhousePrefix):]
		database := new(SQLDatabase)
		database.driver = ClickHouse
		if database.client, err = sql.Open("clickhouse", uri); err != nil {
			return nil, errors.Trace(err)
		}
		database.gormDB, err = gorm.Open(clickhouse.New(clickhouse.Config{Conn: database.client}), gormConfig)
		if err != nil {
			return nil, errors.Trace(err)
		}
		return database, nil

**Comment by zhenghaoz** [comment]
Do you know how to set up a ClickHouse docker container with SSL? I am stuck on this.

This is my config file:

```yaml
# HTTP API with TLS (HTTPS).
# You have to configure certificate to enable this interface.
# See the openSSL section below.
https_port: 8443

# Used with https_port and tcp_port_secure. Full ssl options list: https://github.com/ClickHouse-Extras/poco/blob/master/NetSSL_OpenSSL/include/Poco/Net/SSLManager.h#L71
openSSL:
  server:
    # Used for https server AND secure tcp port
    # openssl req -subj "/CN=localhost" -new -newkey rsa:2048 -days 3650 -nodes -x509 -keyout server.key -out server.crt
    certificateFile: /etc/clickhouse-server/server.crt
    privateKeyFile: /etc/clickhouse-server/server.key
```

But ...
```bash
$ curl https://127.0.0.1:8443 
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:8443 

```
