### ISSUE TITLE
gorse.master container  is always restarting

### ISSUE THREAD

**Issue by cagataygedik** [gorse-io/gorse#542]
```
{"level":"info","ts":1661616150.726118,"caller":"gorse-master/main.go:52","msg":"load config","config":"/etc/gorse/config.toml"}
{"level":"info","ts":1661616150.7347803,"caller":"master/local_cache.go:46","msg":"load cache","path":"/var/lib/gorse/master_cache.data"}
{"level":"info","ts":1661616150.7354877,"caller":"master/master.go:146","msg":"no local cache found, create a new one","path":"/var/lib/gorse/master_cache.data"}
{"level":"fatal","ts":1661616180.7368615,"caller":"master/master.go:195","msg":"failed to init database","error":"server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: mongodb:27017, Type: Unknown, Last error: connection() error occurred during connection handshake: dial tcp: lookup mongodb on 127.0.0.11:53: read udp 127.0.0.1:36845->127.0.0.11:53: i/o timeout }, ] }","errorVerbose":"server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: mongodb:27017, Type: Unknown, Last error: connection() error occurred during connection handshake: dial tcp: lookup mongodb on 127.0.0.11:53: read udp 127.0.0.1:36845->127.0.0.11:53: i/o timeout }, ] }\ngithub.com/zhenghaoz/gorse/storage/data.(*MongoDB).Init:60: ","stacktrace":"github.com/zhenghaoz/gorse/master.(*Master).Serve\n\t/go/gorse/master/master.go:195\nmain.glob..func1\n\t/go/gorse/cmd/gorse-master/main.go:69\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918\nmain.main\n\t/go/gorse/cmd/gorse-master/main.go:84\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
{"level":"info","ts":1661616183.9129517,"caller":"gorse-master/main.go:52","msg":"load config","config":"/etc/gorse/config.toml"}
{"level":"info","ts":1661616183.91963,"caller":"master/local_cache.go:46","msg":"load cache","path":"/var/lib/gorse/master_cache.data"}
{"level":"info","ts":1661616183.9198098,"caller":"master/master.go:146","msg":"no local cache found, create a new one","path":"/var/lib/gorse/master_cache.data"}
{"level":"fatal","ts":1661616213.9218154,"caller":"master/master.go:195","msg":"failed to init database","error":"server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: mongodb:27017, Type: Unknown, Last error: connection() error occurred during connection handshake: dial tcp: lookup mongodb on 127.0.0.11:53: read udp 127.0.0.1:51079->127.0.0.11:53: i/o timeout }, ] }","errorVerbose":"server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: mongodb:27017, Type: Unknown, Last error: connection() error occurred during connection handshake: dial tcp: lookup mongodb on 127.0.0.11:53: read udp 127.0.0.1:51079->127.0.0.11:53: i/o timeout }, ] }\ngithub.com/zhenghaoz/gorse/storage/data.(*MongoDB).Init:60: ","stacktrace":"github.com/zhenghaoz/gorse/master.(*Master).Serve\n\t/go/gorse/master/master.go:195\nmain.glob..func1\n\t/go/gorse/cmd/gorse-master/main.go:69\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918\nmain.main\n\t/go/gorse/cmd/gorse-master/main.go:84\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
{"level":"info","ts":1661616217.2066388,"caller":"gorse-master/main.go:52","msg":"load config","config":"/etc/gorse/config.toml"}
{"level":"info","ts":1661616217.2118216,"caller":"master/local_cache.go:46","msg":"load cache","path":"/var/lib/gorse/master_cache.data"}
{"level":"info","ts":1661616217.2119567,"caller":"master/master.go:146","msg":"no local cache found, create a new one","path":"/var/lib/gorse/master_cache.data"}
{"level":"fatal","ts":1661616247.2135234,"caller":"master/master.go:195","msg":"failed to init database","error":"server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: mongodb:27017, Type: Unknown, Last error: connection() error occurred during connection handshake: dial tcp: lookup mongodb on 127.0.0.11:53: read udp 127.0.0.1:44728->127.0.0.11:53: i/o timeout }, ] }","errorVerbose":"server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: mongodb:27017, Type: Unknown, Last error: connection() error occurred during connection handshake: dial tcp: lookup mongodb on 127.0.0.11:53: read udp 127.0.0.1:44728->127.0.0.11:53: i/o timeout }, ] }\ngithub.com/zhenghaoz/gorse/storage/data.(*MongoDB).Init:60: ","stacktrace":"github.com/zhenghaoz/gorse/master.(*Master).Serve\n\t/go/gorse/master/master.go:195\nmain.glob..func1\n\t/go/gorse/cmd/gorse-master/main.go:69\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918\nmain.main\n\t/go/gorse/cmd/gorse-master/main.go:84\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
{"level":"info","ts":1661616250.9315743,"caller":"gorse-master/main.go:52","msg":"load config","config":"/etc/gorse/config.toml"}
{"level":"info","ts":1661616250.9376345,"caller":"master/local_cache.go:46","msg":"load cache","path":"/var/lib/gorse/master_cache.data"}
{"level":"info","ts":1661616250.937831,"caller":"master/master.go:146","msg":"no local cache found, create a new one","path":"/var/lib/gorse/master_cache.data"}
{"level":"fatal","ts":1661616280.9394588,"caller":"master/master.go:195","msg":"failed to init database","error":"server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: mongodb:27017, Type: Unknown, Last error: connection() error occurred during connection handshake: dial tcp: lookup mongodb: i/o timeout }, ] }","errorVerbose":"server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: mongodb:27017, Type: Unknown, Last error: connection() error occurred during connection handshake: dial tcp: lookup mongodb: i/o timeout }, ] }\ngithub.com/zhenghaoz/gorse/storage/data.(*MongoDB).Init:60: ","stacktrace":"github.com/zhenghaoz/gorse/master.(*Master).Serve\n\t/go/gorse/master/master.go:195\nmain.glob..func1\n\t/go/gorse/cmd/gorse-master/main.go:69\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918\nmain.main\n\t/go/gorse/cmd/gorse-master/main.go:84\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
{"level":"info","ts":1661616284.455413,"caller":"gorse-master/main.go:52","msg":"load config","config":"/etc/gorse/config.toml"}
{"level":"info","ts":1661616284.460811,"caller":"master/local_cache.go:46","msg":"load cache","path":"/var/lib/gorse/master_cache.data"}
{"level":"info","ts":1661616284.460973,"caller":"master/master.go:146","msg":"no local cache found, create a new one","path":"/var/lib/gorse/master_cache.data"}
{"level":"fatal","ts":1661616314.4633322,"caller":"master/master.go:195","msg":"failed to init database","error":"server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: mongodb:27017, Type: Unknown, Last error: connection() error occurred during connection handshake: dial tcp: lookup mongodb on 127.0.0.11:53: read udp 127.0.0.1:37821->127.0.0.11:53: i/o timeout }, ] }","errorVerbose":"server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: mongodb:27017, Type: Unknown, Last error: connection() error occurred during connection handshake: dial tcp: lookup mongodb on 127.0.0.11:53: read udp 127.0.0.1:37821->127.0.0.11:53: i/o timeout }, ] }\ngithub.com/zhenghaoz/gorse/storage/data.(*MongoDB).Init:60: ","stacktrace":"github.com/zhenghaoz/gorse/master.(*Master).Serve\n\t/go/gorse/master/master.go:195\nmain.glob..func1\n\t/go/gorse/cmd/gorse-master/main.go:69\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918\nmain.main\n\t/go/gorse/cmd/gorse-master/main.go:84\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
{"level":"info","ts":1661616317.812413,"caller":"gorse-master/main.go:52","msg":"load config","config":"/etc/gorse/config.toml"}
{"level":"info","ts":1661616317.8192306,"caller":"master/local_cache.go:46","msg":"load cache","path":"/var/lib/gorse/master_cache.data"}
{"level":"info","ts":1661616317.8194172,"caller":"master/master.go:146","msg":"no local cache found, create a new one","path":"/var/lib/gorse/master_cache.data"}
{"level":"fatal","ts":1661616347.8318424,"caller":"master/master.go:195","msg":"failed to init database","error":"server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: mongodb:27017, Type: Unknown, Last error: connection() error occurred during connection handshake: dial tcp: lookup mongodb on 127.0.0.11:53: read udp 127.0.0.1:36667->127.0.0.11:53: i/o timeout }, ] }","errorVerbose":"server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: mongodb:27017, Type: Unknown, Last error: connection() error occurred during connection handshake: dial tcp: lookup mongodb on 127.0.0.11:53: read udp 127.0.0.1:36667->127.0.0.11:53: i/o timeout }, ] }\ngithub.com/zhenghaoz/gorse/storage/data.(*MongoDB).Init:60: ","stacktrace":"github.com/zhenghaoz/gorse/master.(*Master).Serve\n\t/go/gorse/master/master.go:195\nmain.glob..func1\n\t/go/gorse/cmd/gorse-master/main.go:69\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918\nmain.main\n\t/go/gorse/cmd/gorse-master/main.go:84\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
{"level":"info","ts":1661616351.8059578,"caller":"gorse-master/main.go:52","msg":"load config","config":"/etc/gorse/config.toml"}
{"level":"info","ts":1661616351.810459,"caller":"master/local_cache.go:46","msg":"load cache","path":"/var/lib/gorse/master_cache.data"}
{"level":"info","ts":1661616351.8105865,"caller":"master/master.go:146","msg":"no local cache found, create a new one","path":"/var/lib/gorse/master_cache.data"}
{"level":"fatal","ts":1661616381.8117528,"caller":"master/master.go:195","msg":"failed to init database","error":"server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: mongodb:27017, Type: Unknown, Last error: connection() error occurred during connection handshake: dial tcp: lookup mongodb on 127.0.0.11:53: read udp 127.0.0.1:39035->127.0.0.11:53: i/o timeout }, ] }","errorVerbose":"server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: mongodb:27017, Type: Unknown, Last error: connection() error occurred during connection handshake: dial tcp: lookup mongodb on 127.0.0.11:53: read udp 127.0.0.1:39035->127.0.0.11:53: i/o timeout }, ] }\ngithub.com/zhenghaoz/gorse/storage/data.(*MongoDB).Init:60: ","stacktrace":"github.com/zhenghaoz/gorse/master.(*Master).Serve\n\t/go/gorse/master/master.go:195\nmain.glob..func1\n\t/go/gorse/cmd/gorse-master/main.go:69\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918\nmain.main\n\t/go/gorse/cmd/gorse-master/main.go:84\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
{"level":"info","ts":1661616384.959847,"caller":"gorse-master/main.go:52","msg":"load config","config":"/etc/gorse/config.toml"}
{"level":"info","ts":1661616384.9652777,"caller":"master/local_cache.go:46","msg":"load cache","path":"/var/lib/gorse/master_cache.data"}
{"level":"info","ts":1661616384.965398,"caller":"master/master.go:146","msg":"no local cache found, create a new one","path":"/var/lib/gorse/master_cache.data"}
```

I am barely see that I am getting error that "no local cache found, create a new one". How can I fix that? What did I do wrong?

Docker-compose.yml:
```
version: '3'
services:
  app:
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    restart: unless-stopped
  
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    command: mongod
    environment:
      MONGO_INITDB_ROOT_USERNAME: gorse
      MONGO_INITDB_ROOT_PASSWORD: gorse_pass
      MONGO_INITDB_DATABASE: gorse
    volumes:
      - mongodb_data:/data/db

  meilisearch:
    image: getmeili/meilisearch
    restart: unless-stopped
    environment:
      - http_proxy
      - https_proxy
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
      - MEILI_LOG_LEVEL
      - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
    ports:
      - ${MEILI_PORT:-7700}:7700
    networks:
      - meilisearch
    volumes:
      - meilisearch_data:/data.ms

  worker:
    image: zhenghaoz/gorse-worker
    restart: unless-stopped
    ports:
      - 8089:8089
    command: >
      --master-host master 
      --master-port 8086 
      --http-host 0.0.0.0 
      --http-port 8089
      --log-path /var/log/gorse/worker.log 
      --cache-path /var/lib/gorse/worker_cache.data
    volumes:
      - gorse_log:/var/log/gorse
      - worker_data:/var/lib/gorse
    depends_on:
      - master
    

  server:
    image: zhenghaoz/gorse-server
    restart: unless-stopped
    ports:
      - 8087:8087
    command: >
      --master-host master 
      --master-port 8086 
      --http-host 0.0.0.0 
      --http-port 8087
      --log-path /var/log/gorse/server.log 
      --cache-path /var/lib/gorse/server_cache.data
    volumes:
      - gorse_log:/var/log/gorse
      - server_data:/var/lib/gorse
    depends_on:
      - master
    

  master:
    image: zhenghaoz/gorse-master
    restart: unless-stopped
    ports:
      - 8086:8086
      - 8088:8088
    environment:
      GORSE_CACHE_STORE: redis://redis:6379
      GORSE_DATA_STORE: mongodb://gorse:gorse_pass@mongodb:27017/gorse?sslmode=disable
    command: >
      -c /etc/gorse/config.toml 
      --log-path /var/log/gorse/master.log 
      --cache-path /var/lib/gorse/master_cache.data
    volumes:
      - ./config.toml:/etc/gorse/config.toml
      - gorse_log:/var/log/gorse
      - master_data:/var/lib/gorse
    depends_on:
      - mongo
      - redis

volumes:
  mongodb_data:
  worker_data:
  server_data:
  master_data:
  gorse_log:
  meilisearch_data:

networks:
  meilisearch:
    driver: bridge
```
  

Config.toml:
```
[database]

# The database for caching, support Redis, MySQL, Postgres and MongoDB;
cache_store = "redis://localhost:6379/0"

# The database for persist data, support MySQL, Postgres, ClickHouse and MongoDB:
data_store = "mongodb://gorse:gorse_pass@localhost:270117/gorse?sslmode=disable"

# The naming prefix for tables (collections, keys) in databases.
table_prefix = ""


[master]

# GRPC port of the master node. The default value is 8086.
port = 8086

# gRPC host of the master node. The default values is "0.0.0.0".
host = "0.0.0.0"

# HTTP port of the master node. The default values is 8088.
http_port = 8088

# HTTP host of the master node. The default values is "0.0.0.0".
http_host = "0.0.0.0"

# Number of working jobs in the master node. The default value is 1.
n_jobs = 1

# Meta information timeout. The default value is 10s.
meta_timeout = "10s"

# Username for the master node dashboard.
dashboard_user_name = "admin"

# Password for the master node dashboard.
dashboard_password = "admin123"

[server]

# Default number of returned items. The default value is 10.
default_n = 10

# Secret key for RESTful APIs (SSL required).
api_key = ""

# Clock error in the cluster. The default value is 5s.
clock_error = "5s"

# Insert new users while inserting feedback. The default value is true.
auto_insert_user = true

# Insert new items while inserting feedback. The default value is true.
auto_insert_item = false

[recommend]

# The cache size for recommended/popular/latest items. The default value is 10.
cache_size = 100

[recommend.data_source]

# The feedback types for positive events.
positive_feedback_types = ["star","like"]

# The feedback types for read events.
read_feedback_types = ["read"]

# The time-to-live (days) of positive feedback, 0 means disabled. The default value is 0.
positive_feedback_ttl = 0

# The time-to-live (days) of items, 0 means disabled. The default value is 0.
item_ttl = 0

[recommend.popular]

# The time window of popular items. The default values is 4320h.
popular_window = "720h"

[recommend.user_neighbors]

# The type of neighbors for users. There are three types:
#   similar: Neighbors are found by number of common labels.
#   related: Neighbors are found by number of common liked items.
#   auto: If a user have labels, neighbors are found by number of common labels.
#         If this user have no labels, neighbors are found by number of common liked items.
# The default value is "auto".
neighbor_type = "similar"

# Enable approximate user neighbor searching using vector index. The default value is true.
enable_index = true

# Minimal recall for approximate user neighbor searching. The default value is 0.8.
index_recall = 0.8

# Maximal number of fit epochs for approximate user neighbor searching vector index. The default value is 3.
index_fit_epoch = 3

[recommend.item_neighbors]

# The type of neighbors for items. There are three types:
#   similar: Neighbors are found by number of common labels.
#   related: Neighbors are found by number of common users.
#   auto: If a item have labels, neighbors are found by number of common labels.
#         If this item have no labels, neighbors are found by number of common users.
# The default value is "auto".
neighbor_type = "similar"

# Enable approximate item neighbor searching using vector index. The default value is true.
enable_index = false

# Minimal recall for approximate item neighbor searching. The default value is 0.8.
index_recall = 0.8

# Maximal number of fit epochs for approximate item neighbor searching vector index. The default value is 3.
index_fit_epoch = 3

[recommend.collaborative]

# Enable approximate collaborative filtering recommend using vector index. The default value is true.
enable_index = true

# Minimal recall for approximate collaborative filtering recommend. The default value is 0.9.
index_recall = 0.9

# Maximal number of fit epochs for approximate collaborative filtering recommend vector index. The default value is 3.
index_fit_epoch = 3

# The time period for model fitting. The default value is "60m".
model_fit_period = "10m"

# The time period for model searching. The default value is "360m".
model_search_period = "360m"

# The number of epochs for model searching. The default value is 100.
model_search_epoch = 100

# The number of trials for model searching. The default value is 10.
model_search_trials = 10

[recommend.replacement]

# Replace historical items back to recommendations. The default value is false.
enable_replacement = false

# Decay the weights of replaced items from positive feedbacks. The default value is 0.8.
positive_replacement_decay = 0.8

# Decay the weights of replaced items from read feedbacks. The default value is 0.6.
read_replacement_decay = 0.6

[recommend.offline]

# The time period to check recommendation for users. The default values is 1m.
check_recommend_period = "1m"

# The time period to refresh recommendation for inactive users. The default values is 120h.
refresh_recommend_period = "24h"

# Enable latest recommendation during offline recommendation. The default value is false.
enable_latest_recommend = true

# Enable popular recommendation during offline recommendation. The default value is false.
enable_popular_recommend = false

# Enable user-based similarity recommendation during offline recommendation. The default value is false.
enable_user_based_recommend = true

# Enable item-based similarity recommendation during offline recommendation. The default value is false.
enable_item_based_recommend = false

# Enable collaborative filtering recommendation during offline recommendation. The default value is true.
enable_collaborative_recommend = true

# Enable click-though rate prediction during offline recommendation. Otherwise, results from multi-way recommendation
# would be merged randomly. The default value is false.
enable_click_through_prediction = true

# The explore recommendation method is used to inject popular items or latest items into recommended result:
#   popular: Recommend popular items to cold-start users.
#   latest: Recommend latest items to cold-start users.
# The default values is { popular = 0.0, latest = 0.0 }.
explore_recommend = { popular = 0.1, latest = 0.2 }

[recommend.online]

# The fallback recommendation method is used when cached recommendation drained out:
#   item_based: Recommend similar items to cold-start users.
#   popular: Recommend popular items to cold-start users.
#   latest: Recommend latest items to cold-start users.
# Recommenders are used in order. The default values is ["latest"].
fallback_recommend = ["item_based", "latest"]

# The number of feedback used in fallback item-based similar recommendation. The default values is 10.
num_feedback_fallback_item_based = `10`


```</div>

**Comment by NMathar** [comment]
can you try to replace 
GORSE_DATA_STORE: mongodb://gorse:gorse_pass@mongodb:27017/gorse?sslmode=disable
with:
GORSE_DATA_STORE: mongodb://gorse:gorse_pass@mongo:27017/gorse?sslmode=disable

and show us the logs again?

**Comment by zhenghaoz** [comment]
You could try this:

```yaml
version: "3"
services:
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379

  mongo:
    image: mongo:4.0
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: gorse
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  worker:
    image: zhenghaoz/gorse-worker
    restart: unless-stopped
    ports:
      - 8089:8089
    command: >
      --master-host master --master-port 8086 
      --http-host 0.0.0.0 --http-port 8089
      --log-path /var/log/gorse/worker.log 
      --cache-path /var/lib/gorse/worker_cache.data
    volumes:
      - gorse_log:/var/log/gorse
      - worker_data:/var/lib/gorse
    depends_on:
      - master

  server:
    image: zhenghaoz/gorse-server
    restart: unless-stopped
    ports:
      - 8087:8087
    command: >
      --master-host master --master-port 8086 
      --http-host 0.0.0.0 --http-port 8087
      --log-path /var/log/gorse/server.log 
      --cache-path /var/lib/gorse/server_cache.data
    volumes:
      - gorse_log:/var/log/gorse
      - server_data:/var/lib/gorse
    depends_on:
      - master

  master:
    image: zhenghaoz/gorse-master
    restart: unless-stopped
    ports:
      - 8086:8086
      - 8088:8088
    environment:
      GORSE_CACHE_STORE: redis://redis:6379
      GORSE_DATA_STORE: mongodb://root:password@mongo:27017/gorse?authSource=admin&connect=direct
    command: >
      -c /etc/gorse/config.toml 
      --log-path /var/log/gorse/master.log 
      --cache-path /var/lib/gorse/master_cache.data
    volumes:
      - ./config/config.toml.template:/etc/gorse/config.toml
      - gorse_log:/var/log/gorse
      - master_data:/var/lib/gorse
    depends_on:
      - redis
      - mongo

volumes:
  worker_data:
  server_data:
  master_data:
  gorse_log:
  mongo_data:
```
