### ISSUE TITLE
Can't set Redis port number to other than default on Gorse Cluster

### ISSUE THREAD

**Issue by ahndwon** [gorse-io/gorse#689]
Please answer these questions before submitting your issue. Thanks!

**Gorse version**
v0.4.13

**Describe the bug**
I am already using a Gorse cluster on my Mac Mini M1
I am trying to add another cluster for an other project.

Because port number 6379 is already in use,
I have set the Redis port number to 6399 or other number on config.toml and docker-compose.yml.
But connection is refused. 
I get `dial tcp 172.23.0.3:6399: connect:` error when I try the api.
When it is set to default 6379, it works.

I have tried on my macbook also, but same.

I am new to docker, so I could've missed something.

**To Reproduce**
Set Redis port number to other than 6379 on config.toml and docker-compose.yml.

**Expected behavior**
Connect to Redis.

**Additional context**

Redis setting on config.toml
`cache_store = "redis://localhost:6399/0"`

My docker-compose.yml
```
version: "3"
services:
  redis:
   image: redis
   restart: unless-stopped
   ports:
     - 6399:6399

#  mysql:
#    image: mysql/mysql-server
#    restart: unless-stopped
#    ports:
#      - 3306:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: root_pass
#      MYSQL_DATABASE: gorse
#      MYSQL_USER: gorse
#      MYSQL_PASSWORD: gorse_pass
#    volumes:
#      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:10.0
    restart: unless-stopped
    ports:
      - 5532:5532
    environment:
      POSTGRES_DB: gorse
      POSTGRES_USER: gorse
      POSTGRES_PASSWORD: gorse_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # mongo:
  #   image: mongo:4.0
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_DATABASE: gorse
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   volumes:
  #     - mongo_data:/data/db

  # clickhouse:
  #   image: yandex/clickhouse-server:21.10
  #   ports:
  #     - 8123:8123
  #   environment:
  #     CLICKHOUSE_DB: gorse
  #     CLICKHOUSE_USER: gorse
  #     CLICKHOUSE_PASSWORD: gorse_pass
  #   volumes:
  #     - clickhouse_data:/var/lib/clickhouse

  worker:
    image: zhenghaoz/gorse-worker
    restart: unless-stopped
    ports:
      - 8189:8189
    command: >
      --master-host master --master-port 8186 
      --http-host 0.0.0.0 --http-port 8189
      --log-path /var/log/gorse/worker.log 
      --cache-path /var/lib/gorse/worker_cache.data
    volumes:
      - gorse_log:/var/log/gorse
      - worker_data:/var/lib/gorse
    depends_on:
      - master

  server:
    image: zhenghaoz/gorse-server
    restart: unless-stopped
    ports:
      - 8187:8187
    command: >
      --master-host master --master-port 8186 
      --http-host 0.0.0.0 --http-port 8187
      --log-path /var/log/gorse/server.log 
      --cache-path /var/lib/gorse/server_cache.data
    volumes:
      - gorse_log:/var/log/gorse
      - server_data:/var/lib/gorse
    depends_on:
      - master

  master:
    image: zhenghaoz/gorse-master
    restart: unless-stopped
    ports:
      - 8186:8186
      - 8188:8188
    environment:
      GORSE_CACHE_STORE: redis://redis:6399
      # GORSE_CACHE_STORE: postgres://gorse:gorse_pass@postgres/gorse?sslmode=disable
#      GORSE_DATA_STORE: mysql://gorse:gorse_pass@tcp(mysql:3306)/gorse
      GORSE_DATA_STORE: postgres://gorse:gorse_pass@postgres/gorse?sslmode=disable
      # GORSE_DATA_STORE: mongodb://root:password@mongo:27017/gorse?authSource=admin&connect=direct
      # GORSE_DATA_STORE: clickhouse://gorse:gorse_pass@clickhouse:8123/gorse
    command: >
      -c /etc/gorse/config.toml 
      --log-path /var/log/gorse/master.log 
      --cache-path /var/lib/gorse/master_cache.data
    volumes:
      - ./config/config.toml:/etc/gorse/config.toml
      - gorse_log:/var/log/gorse
      - master_data:/var/lib/gorse
    depends_on:
      - redis
      #- mysql
      - postgres
      # - mongo
      # - clickhouse

volumes:
  worker_data:
  server_data:
  master_data:
  gorse_log:
  #mysql_data:
  postgres_data:
  # mongo_data:
  # clickhouse_data:
```

**Comment by ahndwon** [comment]
solved it.
need to add command `--port` to docker-compose.yaml.
```
version: '3.7'
services:
  redis:
    container_name: redis
    hostname: redis
    image: sameersbn/redis:4.0.9-2
    command: --port 6380
    ports:
      - "6380:6380"
    expose:
      - "6380"
```
