### ISSUE TITLE
问题：推荐效果很差

### ISSUE THREAD

**Issue by kiang-codes** [gorse-io/gorse#756]
![image](https://github.com/gorse-io/gorse/assets/61278806/0a7423b9-443f-4362-bedf-54e2089f32ab)
用户对三个商品有feedback，而且仅有三个。
问题1：为什么在基于类别推荐时，标签相似度最高的商品排在了最后一个
问题2：这个商品三个标签都中了，但是在综合推荐时，根本没有推荐出来（后台标签的推荐已经设置为true） 
很期待您的回答，谢谢！

**Comment by zhenghaoz** [comment]
如果你想要推荐标签相似的物品，那么需要这样配置强制系统使用标签推荐

```toml
[recommend.offline]
enable_latest_recommend = false
enable_popular_recommend = false
enable_user_based_recommend = false
enable_item_based_recommend = true
enable_collaborative_recommend = false
enable_click_through_prediction = false
```
