### ISSUE TITLE
Unable to access API after deploying gorse with docker-compose

### ISSUE THREAD

**Issue by HatsuneMK00** [gorse-io/gorse#758]
**Description:**
**Expected Behavior**: I expect to be able to access the API of gorse by using the curl command after successfully deploying it with docker-compose.
**Actual Behavior**: When I use the curl command to access the API, I get the following error message:
`curl: (52) Empty reply from server`
Steps to Reproduce:
	1.	Set up and deploy gorse using docker-compose.
	2.	Use ﻿curl http://localhost:18088/api/user/test1 to access the API.
	3.	Observe the error message received.
Additional Information:
	•	I have followed the docker-compose deployment(using gores-in-one) instructions provided in the gorse-io/gorse repository’s document.
	•	I have checked the docker-compose logs and didn’t find any relevant error messages.
	•	I have verified that the required ports are not being blocked by the firewall.
Environment:
	•	Operating system: [Ubuntu 20.04]
        •      The server has very limited resource, namely 1 vCPU and 2GB RAM.
	•	gorse version: [latest]
Could anyone please assist in resolving this issue? Thank you!

**Comment by zhenghaoz** [comment]
Could you paste your config file and docker compose file here?

**Comment by HatsuneMK00** [comment]
Sure. The main change is the port of data-store, cache-store and server.
`docker-compose.yml`
```yaml
version: "3"
services:
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 16379:6379

  mysql:
    image: mysql/mysql-server
    restart: unless-stopped
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: gorse
      MYSQL_USER: gorse
      MYSQL_PASSWORD: gorse_pass

  gorse:
    image: zhenghaoz/gorse-in-one
    restart: unless-stopped
    ports:
      - 18086:8086   # gRPC port
      - 18088:8088   # HTTP port
    environment:
      # Use Redis as cache storage backend.
      GORSE_CACHE_STORE: redis://redis:6379
      # Use MySQL as data storage backend.
      GORSE_DATA_STORE: mysql://gorse:gorse_pass@tcp(mysql:3306)/gorse?parseTime=true
    command: >
      -c /etc/gorse/config.toml 
      --log-path /var/log/gorse/master.log 
      --cache-path /var/lib/gorse/master_cache.data
    volumes:
      # Mount the configuration file.
      - ./config.toml:/etc/gorse/config.toml
    depends_on:
      - redis
      - mysql
```
`config.toml`
```toml
[database]
cache_store = "redis://localhost:16379/0"
data_store = "mysql://gorse:gorse_pass@tcp(localhost:13306)/gorse"
table_prefix = "whereiscat"
cache_table_prefix = "whereiscat"
data_table_prefix = "whereiscat"
[master]
port = 18086
host = "0.0.0.0"
http_port = 18088
http_host = "0.0.0.0"
http_cors_domains = []
http_cors_methods = []
n_jobs = 1
meta_timeout = "10s"
dashboard_user_name = "admin"
dashboard_password = "123456!"
admin_api_key = ""
[server]
default_n = 5
api_key = ""
clock_error = "5s"
auto_insert_user = true
auto_insert_item = true
cache_expire = "10s"
[recommend]
cache_size = 100
cache_expire = "72h"
[recommend.data_source]
positive_feedback_types = ["like"]
read_feedback_types = ["read"]
positive_feedback_ttl = 0
item_ttl = 0
[recommend.popular]
popular_window = "4320h"
[recommend.user_neighbors]
neighbor_type = "auto"
enable_index = true
index_recall = 0.8
index_fit_epoch = 3
[recommend.item_neighbors]
neighbor_type = "auto"
enable_index = true
index_recall = 0.8
index_fit_epoch = 3
[recommend.collaborative]
enable_index = true
index_recall = 0.9
index_fit_epoch = 3
model_fit_period = "60m"
model_search_period = "360m"
model_search_epoch = 100
model_search_trials = 10
enable_model_size_search = false
[recommend.replacement]
enable_replacement = false
positive_replacement_decay = 0.8
read_replacement_decay = 0.6
[recommend.offline]
check_recommend_period = "1m"
refresh_recommend_period = "120h"
enable_latest_recommend = true
enable_popular_recommend = false
enable_user_based_recommend = true
enable_item_based_recommend = false
enable_collaborative_recommend = true
enable_click_through_prediction = true
explore_recommend = { popular = 0.1, latest = 0.2 }
[recommend.online]
fallback_recommend = ["latest"]
num_feedback_fallback_item_based = 10
[tracing]
enable_tracing = false
exporter = "jaeger"
collector_endpoint = "http://localhost:14268/api/traces"
sampler = "always"
ratio = 1
```
