### ISSUE TITLE
添加测试数据

### ISSUE THREAD

**Issue by homeeecode3** [gorse-io/gorse#839]
使用官方网站：https://gorse.io/ 提供的docker-compose部署：
```yaml
version: "3"
services:
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379

  mysql:
    image: mysql/mysql-server
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: gorse
      MYSQL_USER: gorse
      MYSQL_PASSWORD: gorse_pass

  gorse:
    image: zhenghaoz/gorse-in-one
    restart: unless-stopped
    ports:
      - 8086:8086   # gRPC port
      - 8088:8088   # HTTP port
    environment:
      # Use Redis as cache storage backend.
      GORSE_CACHE_STORE: redis://redis:6379
      # Use MySQL as data storage backend.
      GORSE_DATA_STORE: mysql://gorse:gorse_pass@tcp(mysql:3306)/gorse?parseTime=true
    command: >
      -c /etc/gorse/config.toml
      --log-path /var/log/gorse/master.log
      --cache-path /var/lib/gorse/master_cache.data
    volumes:
      # Mount the configuration file.
      - ./config.toml:/etc/gorse/config.toml
    depends_on:
      - redis
      - mysql
```
启动后也能正常进入面板，但是没有测试数据。
项目是否还在维护？？下载测试数据的SQL文件的时候无法下载，无论是在中国还是泰国，状态码为526，下载命令：
```bash
wget https://cdn.gorse.io/example/github.sql
```
在官方网站跳转https://gitrec.gorse.io/时也无法访问，也是526
